name: Ansible Linter

on:
  push:
    paths:
      - 'playbooks/**'
  pull_request:
    paths:
      - 'playbooks/**'

jobs:
  linter:
    name: Ansible Lint
    runs-on: ubuntu 24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        ansible-lint:
          uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
